### ISSUE TITLE
Cannot remove components from node entities

### ISSUE THREAD

**Issue by jandujar** [BrettJephson/ash-js#7]
Example:

On a system:

for (node = this._listnodes.head; node; node = node.next) {
                var component = new Component();
                node.entity.add(component);
                node.entity.remove(component); <--component not removed
}

**Comment by BrettJephson** [comment]
Hi, 

The problem you are experiencing is because you are trying to remove the instance of the component and not the component type. 

Should be:
node.entity.remove( Component );
Instead of:
node.entity.remove( component );

I.e:
for (node = this._listnodes.head; node; node = node.next) {
var component = new Component();
node.entity.add(component);
node.entity.remove(Component);
}

If you then try console.log( node.entity.has( Component ) ) or console.log( node.entity.get( Component ) ) you should get a false or null value returned, respectively.

**Comment by jandujar** [comment]
For some reason, the entity doesn't have the component, but the nodelist still have the entity, while this entity must be removed from the nodelist (because the nodelist have the component)

Example:

Components:
A, B, C

NodeList
D  -> have components A, B

Entities:
E have components A, B
F have components A, B, C

I remove Component B on the first iteration, on the E entity, but the nodelist still have the entities E & F, and after removing component B from E entity must have only the F entity.

**Comment by BrettJephson** [comment]
Thanks for clarifying. I understand the problem now. I'll add a test and update as soon as I can.

**Comment by jandujar** [comment]
I think this is a critical bug, because the only way to delete a component from an entity is to delete all the entity and create the same entity without this component.

This is something that is happening on my next game due to this error.

**Comment by BrettJephson** [comment]
I've updated the framework with a fix for this problem.
